name: Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.team_cnak4ammfxJtw86SodaJIBnH  }}
  VERCEL_PROJECT_ID: ${{ secrets.prj_FNTi0ewyftraOQordu4hS6AALdmM }}
on:
  push:
    branches:
      - main
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.project1 }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.project1 }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.project1 }}